#!/usr/bin/with-contenv bash

export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/config/plex/Library/Application Support"

# create folders
if [ ! -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" ]; then \
    mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
    chown -R abc:abc /config/plex
fi

# check Library permissions
PUID=${PUID:-911}
if [ ! "$(stat -c %u /config/plex/Library)" = "$PUID" ]; then
    echo "Change in ownership detected, please be patient while we chown existing files"
    echo "This could take some time"
    chown abc:abc -R \
    /config/plex/plex/Library
fi

# remove plex pid after unclean stop
if [[ -f "/config/plex/Library/Application Support/Plex Media Server/plexmediaserver.pid" ]]; then
    rm -f "/config/plex/Library/Application Support/Plex Media Server/plexmediaserver.pid"
fi

# permissions (non-recursive) on config root and folders
chown abc:abc \
    /config/plex \
    /config/plex/*
